"""The guarded exit as a KeeperHub workflow: the same guard, run by KeeperHub's own engine.

``almanak-keeperhub exit`` sends one redeem as ``check-and-execute``: KeeperHub reads the
position right before the write. This module expresses the same decision as a workflow
in KeeperHub's builder, so the guard is a Condition node the operator can read, and the
run is a KeeperHub workflow execution rather than a direct execution:

    Manual trigger (the exit decision: how many shares)
      -> read the wallet's vault shares (ERC-4626 shares are an ERC-20)
      -> Condition: shares held >= shares decided
      -> Morpho vault-redeem(shares, receiver=wallet, owner=wallet)

A stale decision stops at the Condition: the execution completes, the redeem node is
never reached, nothing is broadcast. Free-tier nodes only; the shapes mirror the
compounder in ``keeper.py`` and KeeperHub's own seed workflows.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any

from almanak_keeperhub.keeper import _ref

TRIGGER_LABEL = "Exit decision"
SHARES_LABEL = "Vault shares held"
GATE_LABEL = "Position still covers the decision"
REDEEM_LABEL = "Redeem through KeeperHub"

STATE_FILENAME = "keeperhub-exit-guard.json"


def build_exit_guard_workflow(
    *,
    vault: str,
    chain_id: int,
    wallet: str,
    share_symbol: str = "SHARES",
    name: str | None = None,
) -> dict[str, Any]:
    decided = _ref("trigger", TRIGGER_LABEL, "shares")
    held_raw = _ref("shares", SHARES_LABEL, "balance.balanceRaw")
    network = str(chain_id)
    nodes = [
        {
            "id": "trigger",
            "type": "trigger",
            "data": {
                "type": "trigger",
                "label": TRIGGER_LABEL,
                "config": {"triggerType": "Manual"},
            },
        },
        {
            "id": "shares",
            "type": "action",
            "data": {
                "type": "action",
                "label": SHARES_LABEL,
                "config": {
                    "actionType": "web3/check-token-balance",
                    "network": network,
                    "address": wallet,
                    "tokenConfig": json.dumps(
                        {"mode": "custom", "customToken": {"address": vault, "symbol": share_symbol}}
                    ),
                },
            },
        },
        {
            "id": "gate",
            "type": "action",
            "data": {
                "type": "action",
                "label": GATE_LABEL,
                "config": {
                    "actionType": "Condition",
                    "condition": f"{held_raw} >= {decided}",
                    "conditionConfig": {
                        "group": {
                            "id": "guard",
                            "logic": "AND",
                            "rules": [
                                {
                                    "id": "still-holds",
                                    "operator": ">=",
                                    "leftOperand": held_raw,
                                    "rightOperand": decided,
                                }
                            ],
                        }
                    },
                },
            },
        },
        {
            "id": "redeem",
            "type": "action",
            "data": {
                "type": "action",
                "label": REDEEM_LABEL,
                "config": {
                    "actionType": "morpho/vault-redeem",
                    "network": network,
                    "contractAddress": vault,
                    "shares": decided,
                    "receiver": wallet,
                    "owner": wallet,
                    "_protocolMeta": json.dumps(
                        {
                            "protocolSlug": "morpho",
                            "contractKey": "vault",
                            "functionName": "redeem",
                            "actionType": "write",
                        }
                    ),
                },
            },
        },
    ]
    edges = [
        {"id": "trigger->shares", "source": "trigger", "target": "shares"},
        {"id": "shares->gate", "source": "shares", "target": "gate"},
        {"id": "gate->redeem", "source": "gate", "target": "redeem", "sourceHandle": "true"},
    ]
    return {
        "name": name or f"almanak-keeperhub guarded exit ({vault[:6]}...{vault[-4:]})",
        "description": (
            f'Run with {{"input": {{"shares": N}}}}: read the vault shares {wallet} holds in {vault}; '
            "if they still cover N, redeem N to the wallet. A decision the position no longer covers "
            "stops at the Condition and broadcasts nothing. Generated by almanak-keeperhub."
        ),
        "nodes": nodes,
        "edges": edges,
        "enabled": False,
    }


def state_path(strategy_dir: Path | None = None) -> Path:
    configured = os.environ.get("ALMANAK_KEEPERHUB_EXIT_GUARD_STATE")
    if configured:
        return Path(configured)
    return (strategy_dir or Path.cwd()) / STATE_FILENAME


NODE_ORDER = ("trigger", "shares", "gate", "redeem")


def guard_outcome(result: dict[str, Any]) -> dict[str, Any]:
    """What a finished execution says about the guard: reached the redeem, or stopped at the gate.

    The trace is the workflow's nodes in run order, kept to the ones KeeperHub reports a
    status for; a node the Condition never released has no status at all.
    """
    reported = {
        str(n.get("nodeId")): str(n.get("status") or "") for n in result.get("node_statuses") or [] if n.get("nodeId")
    }
    trace = [f"{node}:{reported[node]}" for node in NODE_ORDER if node in reported]
    trace += [f"{node}:{status}" for node, status in reported.items() if node not in NODE_ORDER]
    hashes = result.get("transaction_hashes") or []
    reached_redeem = "redeem" in reported or any(str(tx.get("nodeId")) == "redeem" for tx in hashes)
    status = str(result.get("status") or "")
    completed = status in ("success", "completed")
    progress = result.get("progress") or {}
    return {
        "executed": reached_redeem and completed and bool(hashes),
        "stopped_at_gate": (not reached_redeem) and completed and "gate" in reported,
        "status": status,
        "trace": trace,
        "steps": f"{progress.get('completedSteps', len(reported))} of {progress.get('totalSteps', len(NODE_ORDER))}",
        "transactions": hashes,
        "error": result.get("error"),
    }
